Vagrant.configure(2) do |config|
  config.vm.box = "plato-trusty"
  config.vm.box_url = "http://http.lab.stgr01.monilytics.net/vagrant/"

  config.vm.communicator = "ssh"
  config.vm.guest = "linux"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "512"
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.name = 'packrat-agent-dev'
  end

  config.vm.network "public_network", auto_config: false

  # plato-client/master setup
  config.vm.provision "file", source: "plato-config.json", destination: "/etc/plato/config.json"

  config.vm.provision "shell", inline: <<-PLATO_CONFIG
set -e
set -x

export DEBIAN_FRONTEND=noninteractive
sed s/--MAC0--/$( cat /sys/class/net/eth0/address )/ -i /etc/plato/config.json
sed s/--MAC1--/$( cat /sys/class/net/eth1/address )/ -i /etc/plato/config.json
sed s/--hostname--/$( hostname )/ -i /etc/plato/config.json
echo "plato-client plato-client/plato-host string file:///etc/plato/config.json" | /usr/bin/debconf-set-selections
dpkg -i /root/plato-client.deb
dpkg -i /root/plato-client-config.deb
wget -q -O- http://repo/repo-key | apt-key add -
apt-get update
ifup eth1
PLATO_CONFIG

  # "install" packrat
  config.vm.synced_folder "../packratAgent", "/usr/lib/python2.7/dist-packages/packratAgent", create: true, :mount_options => ["ro"]
  config.vm.synced_folder "../sbin", "/tmp/sbin", create: true, :mount_options => ["ro"]
  config.vm.provision "file", source: "../sbin/repoSync", destination: "/tmp/repoSync"
  config.vm.provision "file", source: "../templates/packrat-agent/mirror.tpl", destination: "/tmp/mirror.tpl"

  config.vm.provision "shell", inline: <<-PACKRAT_AGENT_CONFIG
set -e
set -x

export DEBIAN_FRONTEND=noninteractive
apt-get install -y python-simplejson python-cinp python-arpy python-gpgme python-rpm yum python-pysqlite2 libsqlite3-0

# "install" the package
ln -s /tmp/sbin/repoSync /usr/sbin/repoSync

mkdir -p /var/lib/packratAgent

mkdir -p /var/lib/plato/templates/packrat-agent/
mv /tmp/mirror.tpl /var/lib/plato/templates/packrat-agent/

configManager -c packrat-agent

PACKRAT_AGENT_CONFIG
end
