{% target '/etc/packrat/mirror.conf' %}# this file is auto generated by configManager do not edit by hand
# generated at {{ timestamp }}
# for device {{ description }}, id: {{ id }}

[packrat]
host: {{ packrat_master_host }}
name: {{ packrat_repo_name }}
psk: {{ packrat_repo_psk }}
proxy: {{ packrat_master_proxy }}

[mirror]
description: {{ pod }}-mirror
root_dir: /var/www/repo
gpg_sign_key:
state_db: /var/lib/packratAgent/state.db
full_sync_interval: 900
keep_file: /var/www/repo/repo-key
{% endtarget %}
