{% target '/etc/packrat/mirror.conf' %}# this file is auto generated by configManager do not edit by hand
# generated at {{ timestamp }}
# for device {{ description }}, id: {{ id }}

[packrat]
host: http://localhost/
name: prod
psk:  prod
proxy:

[repo]
root_dir: /var/www/repo
gpg_sign_key:
{% endtarget %}
